### ISSUE TITLE
DVC

### ISSUE THREAD

**Issue by junxnone** [junxnone/AI#49]
DVC - Data Version Control - Open-source Version Control System for Machine Learning Projects

- 管理数据
- dvc 和 git 协同使用
  - dvc 管理 data
  - git 管理 code
- 控制 pipeline
  - 指定文件记录pipeline 
    - 依赖 -  Data , File
    - 执行命令
    - 输出
  - pipeline 之间可以互相连通
    - stage-1 的输出作为 stage-2 的依赖

# Reference
- [ ] [DVC](https://dvc.org/)
- [ ] [Introduction to DVC](https://www.dazhuanlan.com/2019/10/16/5da68bd45ffda/) 
- [ ] [Github](https://github.com/iterative)
- [ ] [Interactive Tutorials -  Katacoda](https://dvc.org/doc/tutorials/interactive)

# Brief
## Install
```
pip install dvc
```
## Basic UseCase

Command | Description
-- | --
dvc add file/foler | 添加文件(夹)到 dvc , 会产生 `file.dvc`
dvc move file1 file2 | 重命名 dvc file/folder

###  Work with Git

- **1 初始化,  dvc & git 管理相关文件**
  - 获取仓库&数据
  - dvc add 相关数据文件, 获取 data.dvc
  - training 获取 model 文件
  - dvc add model 获取 model.*.dvc
  - git commit dvc 文件

```
git clone https://github.com/iterative/example-versioning.git
cd example-versioning
dvc get https://github.com/iterative/dataset-registry tutorial/ver/data.zip
unzip -q data.zip
rm -f data.zip
dvc add data
python train.py
dvc add model.h5
git add .gitignore model.h5.dvc data.dvc metrics.csv
git commit -m "First model, trained with 1000 images"
git tag -a "v1.0" -m "model v1.0, 1000 images"
```
- **2 更改了数据, 更新dvc & git**
  - 获取新数据, 更新到data文件夹
  - dvc add 更新 data.dvc
  - training model
  - dvc add model file 更新 model.*.dvc
  - git commit dvc 文件

```
dvc get https://github.com/iterative/dataset-registry tutorial/ver/new-labels.zip
unzip -q new-labels.zip
rm -f new-labels.zip
dvc add data
python train.py
dvc add model.h5
git add model.h5.dvc data.dvc metrics.csv
git commit -m "Second model, trained with 2000 images"
git tag -a "v2.0" -m "model v2.0, 2000 images"
```

- **3 获取某个版本的数据**
  - checkout 出相关版本的 `data.dvc` 文件
  - 使用 dvc checkout 出 data 文件夹下的文件

```
git checkout v1.0
  or
git checkout v1.0 data.dvc
dvc checkout
```
- **4 自动化流程**

```
dvc remove -pf model.h5.dvc
dvc run -f dvc/train_t1.dvc \
          -d train.py -d data \
          -M metrics.csv \
          -o model.h5 -o bottleneck_features_train.npy -o bottleneck_features_validation.npy \
          python train.py
git add dvc/train_t1.dvc
git commit -m "training pipeline"
```
> - -f - 指定产生的 DVC-file 名字
> - -d - 依赖文件/文件夹
> - -o - 输出文件
> - -M - metric 文件

<details>
<summary>dvc/train_t1.dvc</summary>
- commands
- deps
- outs

```
$ cat dvc/train_t1.dvc
md5: 8a2113f35f5dff885b9acdcae24d1705
cmd: python train.py
wdir: ..
deps:
- md5: eb3574fe76692fccdb6c12111d5d989c
  path: train.py
- md5: 21060888834f7220846d1c6f6c04e649.dir
  path: data
outs:
- md5: 0e925688e0bb286ddfa5f6086f3c24ee
  path: model.h5
  cache: true
  metric: false
  persist: false
- md5: 6a58a289eb0f82b750701c8e909fbf72
  path: bottleneck_features_train.npy
  cache: true
  metric: false
  persist: false
- md5: 35062f61c29160bb6a8491c8ba90ee2e
  path: bottleneck_features_validation.npy
  cache: true
  metric: false
  persist: false
- md5: 501e48e5356bf3442df055309bc39cf8
  path: metrics.csv
  cache: false
  metric: true
  persist: false
```
</details>

- 4.1 当依赖文件更改时, 重复执行 `pipeline`
```
 dvc repro dvc/train_t1.dvc
```

**Comment by junxnone** [comment]
# TODO
- [ ] [使用 XFS 提升读写性能](https://katacoda.com/dvc/courses/basics/performance) 
- [ ] [git hooks `dvc install`](https://katacoda.com/dvc/courses/basics/versioning)
- [ ] [local repo & ssh remote repo](https://katacoda.com/dvc/courses/basics/sharing)
