### ISSUE TITLE
OpenVINO™ Training Extensions - Training Your labeled Detection Data

### ISSUE THREAD

**Issue by junxnone** [junxnone/AI#81]
- openvino_training_extensions/tensorflow_toolkit/ssd_detector

#  Reference
- [ ] [Github repo](https://github.com/opencv/openvino_training_extensions)

# Brief
- `ssd_detector` 使用 model - `ssd_mobilenet_v2`
- Input_shape - `(256, 256, 3)`
# Prepare Data & Config
## Data - Your Image and Labeled File
- 标注图片
  - 标注工具可以使用`CVAT`, `labelme`, `labelImg` 等
  - 如果有已经标记好的其他格式(Pascal VOC/YOLO)的数据, 可以使用 `CVAT` 预览数据并转换为 `COCO Json` 格式
- 将准备好的图片和注释文件放在 ROOT/data/your_project/
  - 注释文件为 `COCO Json` 格式

## Config
- 参考 `COCO` 和 `VLP` 的配置文件
- 必须配置的选项
  - 标注文件
  - 预训练权重
  - steps
  - lr policy

# Model Training & Evaluation
- 下载在 `COCO datasets` 上预训练的权重用于 `retrain - fine-tune`
```
cd openvino_training_extensions/tensorflow_toolkit/ssd_detector
python3 tools/train.py your_project/config.py
```
- Evaluation 和 Training 同时进行
> 需要手动另起一个终端执行 `eval.py`
```
python3 tools/eval.py your_project/config.py
```

## tensorboard 查看训练过程
```
tensorboard --logdir your_project/model --port your_port
```
> 在浏览器中打开 `127.0.0.1:your_port` 查看训练过程

# Tips
- CVAT dump 的 coco 格式和 此处需要的格式有出入需要把 `file_name` 替换为 `image` - 20200204
- numpy 版本需要低一点的(1.16.4), 否则 eval.py 执行报错 - 20200204

**Comment by junxnone** [comment]
#79 

# TODO
- [ ] Split data(Annotation Json File)
- [ ] evaluation map every classes
